export const initialContacts = [
  {
    id: 1,
    name: 'David Miller',
    email: 'david.miller@example.com',
    phone: '+1 555-0001',
    group: 'Work',
    tags: ['VIP'],
    dateAdded: new Date(2025, 0, 20),
  },
  {
    id: 2,
    name: 'Emma Thompson',
    email: 'emma.thompson@example.com',
    phone: '+1 555-0002',
    group: 'Family',
    tags: ['Urgent', 'Newsletter'],
    dateAdded: new Date(2025, 1, 15),
  },
  {
    id: 3,
    name: 'Liam Wilson',
    email: 'liam.wilson@example.com',
    phone: '+1 555-0003',
    group: 'Friends',
    tags: ['VIP'],
    dateAdded: new Date(2025, 1, 25),
  },
  {
    id: 4,
    name: 'Sophia Martinez',
    email: 'sophia.martinez@example.com',
    phone: '+1 555-0004',
    group: 'Work',
    tags: ['Newsletter'],
    dateAdded: new Date(2025, 2, 3),
  },
  {
    id: 5,
    name: 'James Taylor',
    email: 'james.taylor@example.com',
    phone: '+1 555-0005',
    group: 'Friends',
    tags: [],
    dateAdded: new Date(2025, 2, 10),
  },
  {
    id: 6,
    name: 'Isabella Anderson',
    email: 'isabella.anderson@example.com',
    phone: '+1 555-0006',
    group: 'Family',
    tags: ['Urgent'],
    dateAdded: new Date(2025, 3, 1),
  },
  {
    id: 7,
    name: 'Noah Jackson',
    email: 'noah.jackson@example.com',
    phone: '+1 555-0007',
    group: 'Work',
    tags: ['Newsletter'],
    dateAdded: new Date(2025, 3, 12),
  },
  {
    id: 8,
    name: 'Mia White',
    email: 'mia.white@example.com',
    phone: '+1 555-0008',
    group: 'Friends',
    tags: [],
    dateAdded: new Date(2025, 4, 5),
  },
  {
    id: 9,
    name: 'William Harris',
    email: 'william.harris@example.com',
    phone: '+1 555-0009',
    group: 'Work',
    tags: ['VIP', 'Urgent'],
    dateAdded: new Date(2025, 4, 15),
  },
  {
    id: 10,
    name: 'Olivia Clark',
    email: 'olivia.clark@example.com',
    phone: '+1 555-0010',
    group: 'Family',
    tags: ['Newsletter'],
    dateAdded: new Date(2025, 4, 20),
  },
  {
    id: 11,
    name: 'Lucas Lewis',
    email: 'lucas.lewis@example.com',
    phone: '+1 555-0011',
    group: 'Work',
    tags: [],
    dateAdded: new Date(2025, 5, 1),
  },
  {
    id: 12,
    name: 'Amelia Robinson',
    email: 'amelia.robinson@example.com',
    phone: '+1 555-0012',
    group: 'Friends',
    tags: ['VIP'],
    dateAdded: new Date(2025, 5, 10),
  },
  {
    id: 13,
    name: 'Benjamin Walker',
    email: 'benjamin.walker@example.com',
    phone: '+1 555-0013',
    group: 'Family',
    tags: [],
    dateAdded: new Date(2025, 5, 15),
  },
  {
    id: 14,
    name: 'Charlotte Hall',
    email: 'charlotte.hall@example.com',
    phone: '+1 555-0014',
    group: 'Friends',
    tags: ['Urgent'],
    dateAdded: new Date(2025, 6, 1),
  },
  {
    id: 15,
    name: 'Henry Allen',
    email: 'henry.allen@example.com',
    phone: '+1 555-0015',
    group: 'Work',
    tags: ['VIP'],
    dateAdded: new Date(2025, 6, 5),
  },
  {
    id: 16,
    name: 'Evelyn Young',
    email: 'evelyn.young@example.com',
    phone: '+1 555-0016',
    group: 'Family',
    tags: ['Newsletter'],
    dateAdded: new Date(2025, 6, 10),
  },
  {
    id: 17,
    name: 'Alexander King',
    email: 'alexander.king@example.com',
    phone: '+1 555-0017',
    group: 'Work',
    tags: [],
    dateAdded: new Date(2025, 6, 20),
  },
  {
    id: 18,
    name: 'Harper Wright',
    email: 'harper.wright@example.com',
    phone: '+1 555-0018',
    group: 'Friends',
    tags: ['VIP', 'Newsletter'],
    dateAdded: new Date(2025, 7, 1),
  },
  {
    id: 19,
    name: 'Daniel Lopez',
    email: 'daniel.lopez@example.com',
    phone: '+1 555-0019',
    group: 'Family',
    tags: ['Urgent'],
    dateAdded: new Date(2025, 7, 8),
  },
  {
    id: 20,
    name: 'Avery Hill',
    email: 'avery.hill@example.com',
    phone: '+1 555-0020',
    group: 'Work',
    tags: [],
    dateAdded: new Date(2025, 7, 15),
  },
];
